# Data Preparation

This notebook performs the initial data preparation stage for the project **“Emotional Characterization of Clinical Interview Transcripts in Spanish and English for the Detection of Mild Cognitive Impairment”**.

The goal of this stage is to inspect the available raw audio data, validate the dataset structure, review the ground truth file, and prepare a master metadata table that will support the following steps of the pipeline.

At this stage, the notebook focuses on:

- verifying whether the folder `/original-audio` is available,
- counting how many audio files are stored in that directory,
- identifying the audio formats present in the dataset,
- inspecting the contents of `groundtruth.csv`,
- detecting the language of each available audio file,
- selecting only recordings in Spanish or English for further analysis,
- and creating a master CSV file that will be progressively enriched throughout the project.

This master file will serve as the central reference table for tracking each sample across the complete workflow, including transcription, segmentation, emotion analysis, feature extraction, and classification.

## Raw Audio Directory Check

This section verifies whether the raw audio directory is available.  
The raw audio files were found in `../../../dataset-mineria/original-audio`, which will be used as the input directory for the next preparation steps.

In [4]:
from pathlib import Path

AUDIO_DIR = Path("../../../dataset-mineria/original-audio")

print("Audio directory:", AUDIO_DIR.resolve())
print("Exists:", AUDIO_DIR.exists())
print("Is directory:", AUDIO_DIR.is_dir())

Audio directory: /Users/armando/Developer/dataset-mineria/original-audio
Exists: True
Is directory: True

## Audio File Count and Format Identification

This section counts the number of audio files available in the raw audio directory and identifies the file formats present in the dataset.

In [5]:
from pathlib import Path
from collections import Counter

AUDIO_DIR = Path("../../../dataset-mineria/original-audio")

# Extensiones de audio más comunes
AUDIO_EXTENSIONS = {
    ".wav", ".mp3", ".flac", ".m4a", ".aac", ".ogg", ".wma", ".aiff", ".aif"
}

# Buscar archivos de audio
audio_files = [p for p in AUDIO_DIR.iterdir() if p.is_file() and p.suffix.lower() in AUDIO_EXTENSIONS]

# Contar formatos
format_counts = Counter(p.suffix.lower() for p in audio_files)

print("Audio directory:", AUDIO_DIR.resolve())
print("Exists:", AUDIO_DIR.exists())
print(f"Total audio files found: {len(audio_files)}")
print("\nAudio formats detected:")

for fmt, count in sorted(format_counts.items()):
    print(f"  {fmt}: {count}")

Audio directory: /Users/armando/Developer/dataset-mineria/original-audio
Exists: True
Total audio files found: 387

Audio formats detected:
  .wav: 387

## Ground Truth File Inspection

This section inspects the contents of `groundtruth.csv`, which contains the reference metadata associated with the audio recordings.

In [6]:
from pathlib import Path
import pandas as pd

GROUNDTRUTH_PATH = Path("../../../dataset-mineria/groundtruth.csv")

print("Ground truth path:", GROUNDTRUTH_PATH.resolve())
print("Exists:", GROUNDTRUTH_PATH.exists())

df_gt = pd.read_csv(GROUNDTRUTH_PATH)

print("\nShape:")
print(df_gt.shape)

print("\nColumns:")
print(df_gt.columns.tolist())

print("\nFirst 5 rows:")
display(df_gt.head())

Ground truth path: /Users/armando/Developer/dataset-mineria/groundtruth.csv
Exists: True

Shape:
(387, 5)

Columns:
['tkdname', 'age', 'sex', 'mmse', 'dx']

First 5 rows:

              tkdname  age sex  mmse   dx
0  taukdial-002-1.wav   72   F    29   NC
1  taukdial-002-2.wav   72   F    29   NC
2  taukdial-002-3.wav   72   F    29   NC
3  taukdial-003-1.wav   80   M    23  MCI
4  taukdial-003-2.wav   80   M    23  MCI

## Audio Language Detection

This section identifies the dominant language of each available audio recording.  
The goal is to keep only audio files in Spanish or English, since these are the two languages considered in the project.

In [7]:
from pathlib import Path
import pandas as pd
import whisper

# --------------------------------------------------
# Paths
# --------------------------------------------------
AUDIO_DIR = Path("../../../dataset-mineria/original-audio")

# --------------------------------------------------
# Collect audio files
# --------------------------------------------------
AUDIO_EXTENSIONS = {".wav", ".mp3", ".flac", ".m4a", ".aac", ".ogg", ".wma", ".aiff", ".aif"}
audio_files = sorted([p for p in AUDIO_DIR.iterdir() if p.is_file() and p.suffix.lower() in AUDIO_EXTENSIONS])

print(f"Total audio files found: {len(audio_files)}")

# --------------------------------------------------
# Load Whisper model
# --------------------------------------------------
model = whisper.load_model("base")

# --------------------------------------------------
# Detect language for each audio
# --------------------------------------------------
rows = []

for i, audio_path in enumerate(audio_files, start=1):
    try:
        audio = whisper.load_audio(str(audio_path))
        audio = whisper.pad_or_trim(audio)

        mel = whisper.log_mel_spectrogram(audio).to(model.device)
        _, probs = model.detect_language(mel)

        detected_lang = max(probs, key=probs.get)
        lang_prob = probs[detected_lang]

    except Exception as e:
        detected_lang = None
        lang_prob = None
        print(f"[ERROR] {audio_path.name}: {e}")

    rows.append({
        "audio_file": audio_path.name,
        "audio_stem": audio_path.stem,
        "audio_path": str(audio_path),
        "detected_language": detected_lang,
        "language_probability": lang_prob
    })

    print(f"[{i}/{len(audio_files)}] {audio_path.name} -> {detected_lang} ({lang_prob})")

df_lang = pd.DataFrame(rows)

# --------------------------------------------------
# Keep only Spanish and English
# --------------------------------------------------
LANG_MAP = {
    "en": "English",
    "es": "Spanish"
}

df_lang["language_name"] = df_lang["detected_language"].map(LANG_MAP)
df_lang["is_target_language"] = df_lang["detected_language"].isin(["en", "es"])

print("\nDetected language counts:")
print(df_lang["detected_language"].value_counts(dropna=False))

print("\nTarget language counts (English/Spanish only):")
print(df_lang["language_name"].value_counts(dropna=False))

display(df_lang.head())

Total audio files found: 387
[1/387] taukdial-002-1.wav -> en (0.9992837309837341)
[2/387] taukdial-002-2.wav -> en (0.997840166091919)
[3/387] taukdial-002-3.wav -> en (0.9986321330070496)
[4/387] taukdial-003-1.wav -> zh (0.9693382978439331)
[5/387] taukdial-003-2.wav -> zh (0.9024975299835205)
[6/387] taukdial-003-3.wav -> zh (0.9006768465042114)
[7/387] taukdial-004-1.wav -> my (0.4197703003883362)
[8/387] taukdial-004-2.wav -> my (0.544195294380188)
[9/387] taukdial-004-3.wav -> my (0.4356679618358612)
[10/387] taukdial-005-1.wav -> en (0.9995948672294617)
[11/387] taukdial-005-2.wav -> en (0.9996440410614014)
[12/387] taukdial-005-3.wav -> en (0.9994773268699646)
[13/387] taukdial-006-1.wav -> zh (0.9926403164863586)
[14/387] taukdial-006-2.wav -> zh (0.987817108631134)
[15/387] taukdial-006-3.wav -> zh (0.9835669994354248)
[16/387] taukdial-007-1.wav -> zh (0.9308678507804871)
[17/387] taukdial-007-2.wav -> zh (0.9637993574142456)
[18/387] taukdial-007-3.wav -> zh (0.9486536979675293)
[19/387] taukdial-008-1.wav -> en (0.9982466697692871)
[20/387] taukdial-008-2.wav -> en (0.9991729855537415)
[21/387] taukdial-008-3.wav -> en (0.9988225102424622)
[22/387] taukdial-009-1.wav -> zh (0.9785934686660767)
[23/387] taukdial-009-2.wav -> zh (0.9702333211898804)
[24/387] taukdial-009-3.wav -> zh (0.9777595400810242)
[25/387] taukdial-011-1.wav -> en (0.9982422590255737)
[26/387] taukdial-011-2.wav -> en (0.9952023029327393)
[27/387] taukdial-011-3.wav -> en (0.9984360337257385)
[28/387] taukdial-014-1.wav -> en (0.9988139867782593)
[29/387] taukdial-014-2.wav -> en (0.9993541836738586)
[30/387] taukdial-014-3.wav -> en (0.9993502497673035)
[31/387] taukdial-015-1.wav -> en (0.9986936450004578)
[32/387] taukdial-015-2.wav -> en (0.9985017776489258)
[33/387] taukdial-015-3.wav -> en (0.99906986951828)
[34/387] taukdial-020-1.wav -> en (0.9962782263755798)
[35/387] taukdial-020-2.wav -> en (0.9985848665237427)
[36/387] taukdial-020-3.wav -> en (0.9991750121116638)
[37/387] taukdial-021-1.wav -> zh (0.9957624077796936)
[38/387] taukdial-021-2.wav -> zh (0.9966688752174377)
[39/387] taukdial-021-3.wav -> zh (0.9931288957595825)
[40/387] taukdial-023-1.wav -> zh (0.9943948984146118)
[41/387] taukdial-023-2.wav -> zh (0.9926826357841492)
[42/387] taukdial-023-3.wav -> zh (0.9899175763130188)
[43/387] taukdial-024-1.wav -> zh (0.9648513793945312)
[44/387] taukdial-024-2.wav -> zh (0.9336854219436646)
[45/387] taukdial-024-3.wav -> zh (0.9689671993255615)
[46/387] taukdial-025-1.wav -> zh (0.9905281066894531)
[47/387] taukdial-025-2.wav -> zh (0.9988263249397278)
[48/387] taukdial-025-3.wav -> zh (0.9914932250976562)
[49/387] taukdial-026-1.wav -> en (0.9982878565788269)
[50/387] taukdial-026-2.wav -> en (0.9984492063522339)
[51/387] taukdial-026-3.wav -> en (0.9982665181159973)
[52/387] taukdial-027-1.wav -> zh (0.9934248924255371)
[53/387] taukdial-027-2.wav -> zh (0.9921332597732544)
[54/387] taukdial-027-3.wav -> zh (0.9944705963134766)
[55/387] taukdial-030-1.wav -> en (0.9992400407791138)
[56/387] taukdial-030-2.wav -> en (0.9996492862701416)
[57/387] taukdial-030-3.wav -> en (0.9992916584014893)
[58/387] taukdial-031-1.wav -> en (0.9981380701065063)
[59/387] taukdial-031-2.wav -> en (0.9978265166282654)
[60/387] taukdial-031-3.wav -> en (0.9971544742584229)
[61/387] taukdial-032-1.wav -> en (0.9977850914001465)
[62/387] taukdial-032-2.wav -> en (0.9965533018112183)
[63/387] taukdial-032-3.wav -> en (0.9993042945861816)
[64/387] taukdial-035-1.wav -> en (0.9986829161643982)
[65/387] taukdial-035-2.wav -> en (0.9982976317405701)
[66/387] taukdial-035-3.wav -> en (0.9979167580604553)
[67/387] taukdial-037-1.wav -> en (0.9978463649749756)
[68/387] taukdial-037-2.wav -> en (0.9971659779548645)
[69/387] taukdial-037-3.wav -> en (0.9973821043968201)
[70/387] taukdial-038-1.wav -> en (0.9989437460899353)
[71/387] taukdial-038-2.wav -> en (0.9970943927764893)
[72/387] taukdial-038-3.wav -> en (0.9980998635292053)
[73/387] taukdial-039-1.wav -> zh (0.984491765499115)
[74/387] taukdial-039-2.wav -> zh (0.9925259351730347)
[75/387] taukdial-039-3.wav -> zh (0.9955697655677795)
[76/387] taukdial-040-1.wav -> en (0.9990955591201782)
[77/387] taukdial-040-2.wav -> en (0.999786913394928)
[78/387] taukdial-040-3.wav -> en (0.999355137348175)
[79/387] taukdial-041-1.wav -> en (0.9989860653877258)
[80/387] taukdial-041-2.wav -> en (0.9994907379150391)
[81/387] taukdial-041-3.wav -> en (0.999771773815155)
[82/387] taukdial-044-1.wav -> zh (0.991600751876831)
[83/387] taukdial-044-2.wav -> zh (0.9880870580673218)
[84/387] taukdial-044-3.wav -> zh (0.9909732937812805)
[85/387] taukdial-045-1.wav -> zh (0.9883692264556885)
[86/387] taukdial-045-2.wav -> zh (0.9868248105049133)
[87/387] taukdial-045-3.wav -> zh (0.9746413826942444)
[88/387] taukdial-046-1.wav -> en (0.9960176348686218)
[89/387] taukdial-046-2.wav -> en (0.9987388253211975)
[90/387] taukdial-046-3.wav -> en (0.996121346950531)
[91/387] taukdial-047-1.wav -> zh (0.99146568775177)
[92/387] taukdial-047-2.wav -> zh (0.9931522607803345)
[93/387] taukdial-047-3.wav -> zh (0.9897712469100952)
[94/387] taukdial-048-1.wav -> zh (0.9961007833480835)
[95/387] taukdial-048-2.wav -> zh (0.995173990726471)
[96/387] taukdial-048-3.wav -> zh (0.9847007989883423)
[97/387] taukdial-050-1.wav -> en (0.9988052845001221)
[98/387] taukdial-050-2.wav -> en (0.9985467791557312)
[99/387] taukdial-050-3.wav -> en (0.9992170333862305)
[100/387] taukdial-051-1.wav -> zh (0.9968186616897583)
[101/387] taukdial-051-2.wav -> zh (0.9979277849197388)
[102/387] taukdial-051-3.wav -> zh (0.9971713423728943)
[103/387] taukdial-052-1.wav -> en (0.9997482895851135)
[104/387] taukdial-052-2.wav -> en (0.9995342493057251)
[105/387] taukdial-052-3.wav -> en (0.9972911477088928)
[106/387] taukdial-053-1.wav -> zh (0.9971451163291931)
[107/387] taukdial-053-2.wav -> zh (0.996554970741272)
[108/387] taukdial-053-3.wav -> zh (0.9910248517990112)
[109/387] taukdial-054-1.wav -> zh (0.996206521987915)
[110/387] taukdial-054-2.wav -> zh (0.9941012263298035)
[111/387] taukdial-054-3.wav -> zh (0.9962628483772278)
[112/387] taukdial-056-1.wav -> zh (0.9902465343475342)
[113/387] taukdial-056-2.wav -> zh (0.9695232510566711)
[114/387] taukdial-056-3.wav -> zh (0.9813488125801086)
[115/387] taukdial-057-1.wav -> en (0.9984003901481628)
[116/387] taukdial-057-2.wav -> en (0.9997509121894836)
[117/387] taukdial-057-3.wav -> en (0.9982075691223145)
[118/387] taukdial-063-1.wav -> zh (0.9852684140205383)
[119/387] taukdial-063-2.wav -> zh (0.9983166456222534)
[120/387] taukdial-063-3.wav -> zh (0.9930458664894104)
[121/387] taukdial-064-1.wav -> zh (0.9880045056343079)
[122/387] taukdial-064-2.wav -> zh (0.989727795124054)
[123/387] taukdial-064-3.wav -> zh (0.9698368906974792)
[124/387] taukdial-065-1.wav -> zh (0.9931756854057312)
[125/387] taukdial-065-2.wav -> zh (0.9924627542495728)
[126/387] taukdial-065-3.wav -> zh (0.9886462688446045)
[127/387] taukdial-066-1.wav -> zh (0.9884682297706604)
[128/387] taukdial-066-2.wav -> zh (0.960418164730072)
[129/387] taukdial-066-3.wav -> zh (0.9171565175056458)
[130/387] taukdial-067-1.wav -> zh (0.9490980505943298)
[131/387] taukdial-067-2.wav -> zh (0.9923810362815857)
[132/387] taukdial-067-3.wav -> zh (0.9776109457015991)
[133/387] taukdial-068-1.wav -> en (0.9988866448402405)
[134/387] taukdial-068-2.wav -> en (0.9996582269668579)
[135/387] taukdial-068-3.wav -> en (0.9994146823883057)
[136/387] taukdial-069-1.wav -> en (0.9962570667266846)
[137/387] taukdial-069-2.wav -> en (0.9977395534515381)
[138/387] taukdial-069-3.wav -> en (0.9970393180847168)
[139/387] taukdial-070-1.wav -> en (0.9985935091972351)
[140/387] taukdial-070-2.wav -> en (0.9993767142295837)
[141/387] taukdial-070-3.wav -> en (0.9937680959701538)
[142/387] taukdial-071-1.wav -> en (0.9986844658851624)
[143/387] taukdial-071-2.wav -> en (0.9994914531707764)
[144/387] taukdial-071-3.wav -> en (0.9982262253761292)
[145/387] taukdial-072-1.wav -> zh (0.9868354797363281)
[146/387] taukdial-072-2.wav -> zh (0.9962241649627686)
[147/387] taukdial-072-3.wav -> zh (0.9920769929885864)
[148/387] taukdial-073-1.wav -> zh (0.9904012084007263)
[149/387] taukdial-073-2.wav -> zh (0.9894834160804749)
[150/387] taukdial-073-3.wav -> zh (0.9631434679031372)
[151/387] taukdial-074-1.wav -> en (0.9989745616912842)
[152/387] taukdial-074-2.wav -> en (0.999782383441925)
[153/387] taukdial-074-3.wav -> en (0.9991877675056458)
[154/387] taukdial-076-1.wav -> en (0.9981763362884521)
[155/387] taukdial-076-2.wav -> en (0.9988806843757629)
[156/387] taukdial-076-3.wav -> en (0.9982349872589111)
[157/387] taukdial-077-1.wav -> en (0.9983397722244263)
[158/387] taukdial-077-2.wav -> en (0.999377429485321)
[159/387] taukdial-077-3.wav -> en (0.9983783960342407)
[160/387] taukdial-078-1.wav -> en (0.9976133108139038)
[161/387] taukdial-078-2.wav -> en (0.9979212880134583)
[162/387] taukdial-078-3.wav -> en (0.9981391429901123)
[163/387] taukdial-079-1.wav -> en (0.9985311031341553)
[164/387] taukdial-079-2.wav -> en (0.9981560111045837)
[165/387] taukdial-079-3.wav -> en (0.9976741671562195)
[166/387] taukdial-080-1.wav -> zh (0.9975253939628601)
[167/387] taukdial-080-2.wav -> zh (0.9885777235031128)
[168/387] taukdial-080-3.wav -> zh (0.795222818851471)
[169/387] taukdial-082-1.wav -> zh (0.9942843317985535)
[170/387] taukdial-082-2.wav -> zh (0.9903954863548279)
[171/387] taukdial-082-3.wav -> zh (0.995526134967804)
[172/387] taukdial-083-1.wav -> en (0.99880051612854)
[173/387] taukdial-083-2.wav -> en (0.9986435770988464)
[174/387] taukdial-083-3.wav -> en (0.9982696771621704)
[175/387] taukdial-085-1.wav -> en (0.9995083808898926)
[176/387] taukdial-085-2.wav -> en (0.999270498752594)
[177/387] taukdial-085-3.wav -> en (0.9992853999137878)
[178/387] taukdial-086-1.wav -> zh (0.982593834400177)
[179/387] taukdial-086-2.wav -> zh (0.9948093891143799)
[180/387] taukdial-086-3.wav -> zh (0.986825168132782)
[181/387] taukdial-088-1.wav -> en (0.9996516704559326)
[182/387] taukdial-088-2.wav -> en (0.9994231462478638)
[183/387] taukdial-088-3.wav -> en (0.9997729659080505)
[184/387] taukdial-089-1.wav -> en (0.9990749359130859)
[185/387] taukdial-089-2.wav -> en (0.9994482398033142)
[186/387] taukdial-089-3.wav -> en (0.9986315369606018)
[187/387] taukdial-090-1.wav -> zh (0.9897418022155762)
[188/387] taukdial-090-2.wav -> zh (0.9982536435127258)
[189/387] taukdial-090-3.wav -> zh (0.9947810769081116)
[190/387] taukdial-091-1.wav -> en (0.9980564117431641)
[191/387] taukdial-091-2.wav -> en (0.9987744688987732)
[192/387] taukdial-091-3.wav -> en (0.9985103011131287)
[193/387] taukdial-092-1.wav -> zh (0.9967232346534729)
[194/387] taukdial-092-2.wav -> zh (0.9924172163009644)
[195/387] taukdial-092-3.wav -> zh (0.9954303503036499)
[196/387] taukdial-093-1.wav -> zh (0.9893409609794617)
[197/387] taukdial-093-2.wav -> zh (0.99664306640625)
[198/387] taukdial-093-3.wav -> zh (0.988129198551178)
[199/387] taukdial-094-1.wav -> zh (0.9937071204185486)
[200/387] taukdial-094-2.wav -> zh (0.9892134070396423)
[201/387] taukdial-094-3.wav -> zh (0.9937456846237183)
[202/387] taukdial-095-1.wav -> en (0.9983933568000793)
[203/387] taukdial-095-2.wav -> en (0.9965852499008179)
[204/387] taukdial-095-3.wav -> en (0.9967808723449707)
[205/387] taukdial-096-1.wav -> zh (0.9628039002418518)
[206/387] taukdial-096-2.wav -> zh (0.9941428303718567)
[207/387] taukdial-096-3.wav -> zh (0.9921910166740417)
[208/387] taukdial-097-1.wav -> zh (0.9886773824691772)
[209/387] taukdial-097-2.wav -> zh (0.9844501614570618)
[210/387] taukdial-097-3.wav -> zh (0.9779112935066223)
[211/387] taukdial-098-1.wav -> zh (0.9953688979148865)
[212/387] taukdial-098-2.wav -> zh (0.9987269043922424)
[213/387] taukdial-098-3.wav -> zh (0.9925590753555298)
[214/387] taukdial-099-1.wav -> en (0.9980499744415283)
[215/387] taukdial-099-2.wav -> en (0.9974924325942993)
[216/387] taukdial-099-3.wav -> en (0.9976227879524231)
[217/387] taukdial-100-1.wav -> bo (0.6642001867294312)
[218/387] taukdial-100-2.wav -> zh (0.9859974384307861)
[219/387] taukdial-100-3.wav -> zh (0.9702966213226318)
[220/387] taukdial-101-1.wav -> en (0.997836172580719)
[221/387] taukdial-101-2.wav -> en (0.9995906949043274)
[222/387] taukdial-101-3.wav -> en (0.9981446266174316)
[223/387] taukdial-102-1.wav -> en (0.9993071556091309)
[224/387] taukdial-102-2.wav -> en (0.9993964433670044)
[225/387] taukdial-102-3.wav -> en (0.9991081357002258)
[226/387] taukdial-104-1.wav -> en (0.999011754989624)
[227/387] taukdial-104-2.wav -> en (0.9980365633964539)
[228/387] taukdial-104-3.wav -> en (0.9994575381278992)
[229/387] taukdial-105-1.wav -> zh (0.9959548711776733)
[230/387] taukdial-105-2.wav -> zh (0.9945032596588135)
[231/387] taukdial-105-3.wav -> zh (0.9890016317367554)
[232/387] taukdial-106-1.wav -> zh (0.9806862473487854)
[233/387] taukdial-106-2.wav -> zh (0.988179087638855)
[234/387] taukdial-106-3.wav -> zh (0.9816967844963074)
[235/387] taukdial-107-1.wav -> zh (0.9928064346313477)
[236/387] taukdial-107-2.wav -> zh (0.9960229396820068)
[237/387] taukdial-107-3.wav -> zh (0.9787753820419312)
[238/387] taukdial-108-1.wav -> zh (0.9642221331596375)
[239/387] taukdial-108-2.wav -> zh (0.978683352470398)
[240/387] taukdial-108-3.wav -> zh (0.9496456980705261)
[241/387] taukdial-109-1.wav -> zh (0.988811731338501)
[242/387] taukdial-109-2.wav -> zh (0.995344340801239)
[243/387] taukdial-109-3.wav -> zh (0.9971644282341003)
[244/387] taukdial-110-1.wav -> zh (0.9759954810142517)
[245/387] taukdial-110-2.wav -> zh (0.9556285738945007)
[246/387] taukdial-110-3.wav -> zh (0.9548516869544983)
[247/387] taukdial-111-1.wav -> zh (0.9920712113380432)
[248/387] taukdial-111-2.wav -> zh (0.9901890158653259)
[249/387] taukdial-111-3.wav -> zh (0.9909712076187134)
[250/387] taukdial-112-1.wav -> en (0.9969419836997986)
[251/387] taukdial-112-2.wav -> en (0.9990859031677246)
[252/387] taukdial-112-3.wav -> en (0.9958498477935791)
[253/387] taukdial-113-1.wav -> en (0.9986950755119324)
[254/387] taukdial-113-2.wav -> en (0.9994480013847351)
[255/387] taukdial-113-3.wav -> en (0.9993597865104675)
[256/387] taukdial-115-1.wav -> en (0.9994348883628845)
[257/387] taukdial-115-2.wav -> en (0.9994682669639587)
[258/387] taukdial-115-3.wav -> en (0.9995076656341553)
[259/387] taukdial-116-1.wav -> en (0.9987934827804565)
[260/387] taukdial-116-2.wav -> en (0.9996154308319092)
[261/387] taukdial-116-3.wav -> en (0.9982553124427795)
[262/387] taukdial-117-1.wav -> en (0.9996324777603149)
[263/387] taukdial-117-2.wav -> en (0.9993107318878174)
[264/387] taukdial-117-3.wav -> en (0.9996272325515747)
[265/387] taukdial-118-1.wav -> en (0.9975850582122803)
[266/387] taukdial-118-2.wav -> en (0.998794436454773)
[267/387] taukdial-118-3.wav -> en (0.9981447458267212)
[268/387] taukdial-120-1.wav -> en (0.9988871216773987)
[269/387] taukdial-120-2.wav -> en (0.9992700219154358)
[270/387] taukdial-120-3.wav -> en (0.9985601305961609)
[271/387] taukdial-121-1.wav -> zh (0.98052978515625)
[272/387] taukdial-121-2.wav -> zh (0.9882633686065674)
[273/387] taukdial-121-3.wav -> zh (0.9930818676948547)
[274/387] taukdial-122-1.wav -> my (0.5936365723609924)
[275/387] taukdial-122-2.wav -> zh (0.5191174745559692)
[276/387] taukdial-122-3.wav -> zh (0.6921693086624146)
[277/387] taukdial-124-1.wav -> en (0.9957824945449829)
[278/387] taukdial-124-2.wav -> en (0.9995286464691162)
[279/387] taukdial-124-3.wav -> en (0.9991625547409058)
[280/387] taukdial-125-1.wav -> en (0.9977444410324097)
[281/387] taukdial-125-2.wav -> en (0.9965221881866455)
[282/387] taukdial-125-3.wav -> en (0.9997305274009705)
[283/387] taukdial-126-1.wav -> en (0.9965768456459045)
[284/387] taukdial-126-2.wav -> en (0.9982414245605469)
[285/387] taukdial-126-3.wav -> en (0.9937704205513)
[286/387] taukdial-127-1.wav -> zh (0.9961736798286438)
[287/387] taukdial-127-2.wav -> zh (0.9982288479804993)
[288/387] taukdial-127-3.wav -> zh (0.9902064204216003)
[289/387] taukdial-128-1.wav -> zh (0.9888961315155029)
[290/387] taukdial-128-2.wav -> zh (0.9933131337165833)
[291/387] taukdial-128-3.wav -> zh (0.9595789909362793)
[292/387] taukdial-129-1.wav -> zh (0.9880350232124329)
[293/387] taukdial-129-2.wav -> zh (0.9676730632781982)
[294/387] taukdial-129-3.wav -> zh (0.9790431261062622)
[295/387] taukdial-130-1.wav -> zh (0.9866395592689514)
[296/387] taukdial-130-2.wav -> zh (0.9804685115814209)
[297/387] taukdial-130-3.wav -> zh (0.9843472242355347)
[298/387] taukdial-131-1.wav -> zh (0.972647488117218)
[299/387] taukdial-131-2.wav -> zh (0.9919954538345337)
[300/387] taukdial-131-3.wav -> zh (0.9845753908157349)
[301/387] taukdial-132-1.wav -> zh (0.9843761920928955)
[302/387] taukdial-132-2.wav -> zh (0.9982865452766418)
[303/387] taukdial-132-3.wav -> zh (0.9600148797035217)
[304/387] taukdial-134-1.wav -> zh (0.9905101656913757)
[305/387] taukdial-134-2.wav -> zh (0.9923090934753418)
[306/387] taukdial-134-3.wav -> zh (0.9931650757789612)
[307/387] taukdial-136-1.wav -> zh (0.9530856609344482)
[308/387] taukdial-136-2.wav -> zh (0.9354619383811951)
[309/387] taukdial-136-3.wav -> zh (0.9589183330535889)
[310/387] taukdial-137-1.wav -> en (0.998158872127533)
[311/387] taukdial-137-2.wav -> en (0.9977555871009827)
[312/387] taukdial-137-3.wav -> en (0.9992233514785767)
[313/387] taukdial-138-1.wav -> en (0.9990313053131104)
[314/387] taukdial-138-2.wav -> en (0.9996680021286011)
[315/387] taukdial-138-3.wav -> en (0.9991645812988281)
[316/387] taukdial-139-1.wav -> en (0.999729335308075)
[317/387] taukdial-139-2.wav -> en (0.9996511936187744)
[318/387] taukdial-139-3.wav -> en (0.9993002414703369)
[319/387] taukdial-140-1.wav -> en (0.9980947375297546)
[320/387] taukdial-140-2.wav -> en (0.9993118047714233)
[321/387] taukdial-140-3.wav -> en (0.9984415173530579)
[322/387] taukdial-141-1.wav -> zh (0.9689812064170837)
[323/387] taukdial-141-2.wav -> zh (0.9801827669143677)
[324/387] taukdial-141-3.wav -> zh (0.9756284952163696)
[325/387] taukdial-142-1.wav -> zh (0.9948430061340332)
[326/387] taukdial-142-2.wav -> zh (0.9965764880180359)
[327/387] taukdial-142-3.wav -> zh (0.9960630536079407)
[328/387] taukdial-143-1.wav -> zh (0.9807890057563782)
[329/387] taukdial-143-2.wav -> zh (0.9740831255912781)
[330/387] taukdial-143-3.wav -> zh (0.9872493147850037)
[331/387] taukdial-144-1.wav -> zh (0.9907382130622864)
[332/387] taukdial-144-2.wav -> zh (0.9954473376274109)
[333/387] taukdial-144-3.wav -> zh (0.9846413731575012)
[334/387] taukdial-145-1.wav -> en (0.9968850016593933)
[335/387] taukdial-145-2.wav -> en (0.996856689453125)
[336/387] taukdial-145-3.wav -> en (0.9970855116844177)
[337/387] taukdial-148-1.wav -> en (0.9972802400588989)
[338/387] taukdial-148-2.wav -> en (0.9991573095321655)
[339/387] taukdial-148-3.wav -> en (0.9980227947235107)
[340/387] taukdial-149-1.wav -> en (0.9992840886116028)
[341/387] taukdial-149-2.wav -> en (0.9994266033172607)
[342/387] taukdial-149-3.wav -> en (0.999854564666748)
[343/387] taukdial-151-1.wav -> en (0.9981108903884888)
[344/387] taukdial-151-2.wav -> en (0.9980238676071167)
[345/387] taukdial-151-3.wav -> en (0.9992706179618835)
[346/387] taukdial-153-1.wav -> zh (0.9884703159332275)
[347/387] taukdial-153-2.wav -> zh (0.9982831478118896)
[348/387] taukdial-153-3.wav -> zh (0.9901052117347717)
[349/387] taukdial-154-1.wav -> en (0.999562680721283)
[350/387] taukdial-154-2.wav -> en (0.9993889331817627)
[351/387] taukdial-154-3.wav -> en (0.998664379119873)
[352/387] taukdial-156-1.wav -> zh (0.9934478402137756)
[353/387] taukdial-156-2.wav -> zh (0.9970889687538147)
[354/387] taukdial-156-3.wav -> zh (0.9961879849433899)
[355/387] taukdial-157-1.wav -> zh (0.9670194983482361)
[356/387] taukdial-157-2.wav -> zh (0.9634929299354553)
[357/387] taukdial-157-3.wav -> zh (0.9074348211288452)
[358/387] taukdial-158-1.wav -> en (0.9992759823799133)
[359/387] taukdial-158-2.wav -> en (0.9993374943733215)

,audio_file,audio_stem,audio_path,detected_language,language_probability,language_name,is_target_language
0,taukdial-002-1.wav,taukdial-002-1,../../../dataset-mineria/original-audio/taukdi...,en,0.999284,English,True
1,taukdial-002-2.wav,taukdial-002-2,../../../dataset-mineria/original-audio/taukdi...,en,0.997840,English,True
2,taukdial-002-3.wav,taukdial-002-3,../../../dataset-mineria/original-audio/taukdi...,en,0.998632,English,True
3,taukdial-003-1.wav,taukdial-003-1,../../../dataset-mineria/original-audio/taukdi...,zh,0.969338,NaN,False
4,taukdial-003-2.wav,taukdial-003-2,../../../dataset-mineria/original-audio/taukdi...,zh,0.902498,NaN,False

## Master Metadata Initialization

At this stage, the project begins the construction of a master metadata table.  
This table integrates the available audio file information, the detected language for each recording, and the reference information provided in `groundtruth.csv`.

The master CSV will be progressively enriched in later stages of the pipeline, serving as the central file for traceability and analysis.

In [12]:
from pathlib import Path
import pandas as pd
import whisper

# ==================================================
# Paths
# ==================================================
DATASET_DIR = Path("../../../dataset-mineria")
AUDIO_DIR = DATASET_DIR / "original-audio"
GROUNDTRUTH_PATH = DATASET_DIR / "groundtruth.csv"
OUTPUT_DIR = Path("./outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

MASTER_CSV_PATH = OUTPUT_DIR / "master_metadata.csv"

# ==================================================
# Load ground truth
# ==================================================
df_gt = pd.read_csv(GROUNDTRUTH_PATH)

# Clean merge key in ground truth
df_gt = df_gt.copy()
df_gt["audio_file"] = df_gt["tkdname"].astype(str).str.strip()

# ==================================================
# Collect audio files
# ==================================================
AUDIO_EXTENSIONS = {
    ".wav", ".mp3", ".flac", ".m4a", ".aac", ".ogg", ".wma", ".aiff", ".aif"
}

audio_files = sorted([
    p for p in AUDIO_DIR.iterdir()
    if p.is_file() and p.suffix.lower() in AUDIO_EXTENSIONS
])

print(f"Total audio files found: {len(audio_files)}")

# ==================================================
# Load Whisper model
# ==================================================
model = whisper.load_model("base")

# ==================================================
# Detect language and build audio table
# ==================================================
rows = []

for i, audio_path in enumerate(audio_files, start=1):
    try:
        audio = whisper.load_audio(str(audio_path))
        audio = whisper.pad_or_trim(audio)

        mel = whisper.log_mel_spectrogram(audio).to(model.device)
        _, probs = model.detect_language(mel)

        detected_lang = max(probs, key=probs.get)
        lang_prob = probs[detected_lang]

    except Exception as e:
        detected_lang = None
        lang_prob = None
        print(f"[ERROR] {audio_path.name}: {e}")

    rows.append({
        "audio_file": audio_path.name,
        "audio_stem": audio_path.stem,
        "audio_path": str(audio_path),
        "audio_extension": audio_path.suffix.lower(),
        "detected_language": detected_lang,
        "language_probability": lang_prob,
        "language_name": {
            "en": "English",
            "es": "Spanish",
            "zh": "Chinese",
            "my": "Burmese"
        }.get(detected_lang, "Other"),
        "is_target_language": detected_lang in {"en", "es"}
    })

    print(f"[{i}/{len(audio_files)}] {audio_path.name} -> {detected_lang} ({lang_prob})")

df_audio = pd.DataFrame(rows)

# ==================================================
# Merge with ground truth using full file name
# ==================================================
master_df = df_audio.merge(df_gt, on="audio_file", how="left")

# ==================================================
# Save master CSV
# ==================================================
master_df.to_csv(MASTER_CSV_PATH, index=False)

print("\nSaved:", MASTER_CSV_PATH.resolve())
print("Shape:", master_df.shape)

print("\nPreview of merged columns:")
print(master_df[["audio_file", "tkdname", "age", "sex", "mmse", "dx"]].head(10))

Total audio files found: 387
[1/387] taukdial-002-1.wav -> en (0.9992837309837341)
[2/387] taukdial-002-2.wav -> en (0.997840166091919)
[3/387] taukdial-002-3.wav -> en (0.9986321330070496)
[4/387] taukdial-003-1.wav -> zh (0.9693382978439331)
[5/387] taukdial-003-2.wav -> zh (0.9024975299835205)
[6/387] taukdial-003-3.wav -> zh (0.9006768465042114)
[7/387] taukdial-004-1.wav -> my (0.4197703003883362)
[8/387] taukdial-004-2.wav -> my (0.544195294380188)
[9/387] taukdial-004-3.wav -> my (0.4356679618358612)
[10/387] taukdial-005-1.wav -> en (0.9995948672294617)
[11/387] taukdial-005-2.wav -> en (0.9996440410614014)
[12/387] taukdial-005-3.wav -> en (0.9994773268699646)
[13/387] taukdial-006-1.wav -> zh (0.9926403164863586)
[14/387] taukdial-006-2.wav -> zh (0.987817108631134)
[15/387] taukdial-006-3.wav -> zh (0.9835669994354248)
[16/387] taukdial-007-1.wav -> zh (0.9308678507804871)
[17/387] taukdial-007-2.wav -> zh (0.9637993574142456)
[18/387] taukdial-007-3.wav -> zh (0.9486536979675293)
[19/387] taukdial-008-1.wav -> en (0.9982466697692871)
[20/387] taukdial-008-2.wav -> en (0.9991729855537415)
[21/387] taukdial-008-3.wav -> en (0.9988225102424622)
[22/387] taukdial-009-1.wav -> zh (0.9785934686660767)
[23/387] taukdial-009-2.wav -> zh (0.9702333211898804)
[24/387] taukdial-009-3.wav -> zh (0.9777595400810242)
[25/387] taukdial-011-1.wav -> en (0.9982422590255737)
[26/387] taukdial-011-2.wav -> en (0.9952023029327393)
[27/387] taukdial-011-3.wav -> en (0.9984360337257385)
[28/387] taukdial-014-1.wav -> en (0.9988139867782593)
[29/387] taukdial-014-2.wav -> en (0.9993541836738586)
[30/387] taukdial-014-3.wav -> en (0.9993502497673035)
[31/387] taukdial-015-1.wav -> en (0.9986936450004578)
[32/387] taukdial-015-2.wav -> en (0.9985017776489258)
[33/387] taukdial-015-3.wav -> en (0.99906986951828)
[34/387] taukdial-020-1.wav -> en (0.9962782263755798)
[35/387] taukdial-020-2.wav -> en (0.9985848665237427)
[36/387] taukdial-020-3.wav -> en (0.9991750121116638)
[37/387] taukdial-021-1.wav -> zh (0.9957624077796936)
[38/387] taukdial-021-2.wav -> zh (0.9966688752174377)
[39/387] taukdial-021-3.wav -> zh (0.9931288957595825)
[40/387] taukdial-023-1.wav -> zh (0.9943948984146118)
[41/387] taukdial-023-2.wav -> zh (0.9926826357841492)
[42/387] taukdial-023-3.wav -> zh (0.9899175763130188)
[43/387] taukdial-024-1.wav -> zh (0.9648513793945312)
[44/387] taukdial-024-2.wav -> zh (0.9336854219436646)
[45/387] taukdial-024-3.wav -> zh (0.9689671993255615)
[46/387] taukdial-025-1.wav -> zh (0.9905281066894531)
[47/387] taukdial-025-2.wav -> zh (0.9988263249397278)
[48/387] taukdial-025-3.wav -> zh (0.9914932250976562)
[49/387] taukdial-026-1.wav -> en (0.9982878565788269)
[50/387] taukdial-026-2.wav -> en (0.9984492063522339)
[51/387] taukdial-026-3.wav -> en (0.9982665181159973)
[52/387] taukdial-027-1.wav -> zh (0.9934248924255371)
[53/387] taukdial-027-2.wav -> zh (0.9921332597732544)
[54/387] taukdial-027-3.wav -> zh (0.9944705963134766)
[55/387] taukdial-030-1.wav -> en (0.9992400407791138)
[56/387] taukdial-030-2.wav -> en (0.9996492862701416)
[57/387] taukdial-030-3.wav -> en (0.9992916584014893)
[58/387] taukdial-031-1.wav -> en (0.9981380701065063)
[59/387] taukdial-031-2.wav -> en (0.9978265166282654)
[60/387] taukdial-031-3.wav -> en (0.9971544742584229)
[61/387] taukdial-032-1.wav -> en (0.9977850914001465)
[62/387] taukdial-032-2.wav -> en (0.9965533018112183)
[63/387] taukdial-032-3.wav -> en (0.9993042945861816)
[64/387] taukdial-035-1.wav -> en (0.9986829161643982)
[65/387] taukdial-035-2.wav -> en (0.9982976317405701)
[66/387] taukdial-035-3.wav -> en (0.9979167580604553)
[67/387] taukdial-037-1.wav -> en (0.9978463649749756)
[68/387] taukdial-037-2.wav -> en (0.9971659779548645)
[69/387] taukdial-037-3.wav -> en (0.9973821043968201)
[70/387] taukdial-038-1.wav -> en (0.9989437460899353)
[71/387] taukdial-038-2.wav -> en (0.9970943927764893)
[72/387] taukdial-038-3.wav -> en (0.9980998635292053)
[73/387] taukdial-039-1.wav -> zh (0.984491765499115)
[74/387] taukdial-039-2.wav -> zh (0.9925259351730347)
[75/387] taukdial-039-3.wav -> zh (0.9955697655677795)
[76/387] taukdial-040-1.wav -> en (0.9990955591201782)
[77/387] taukdial-040-2.wav -> en (0.999786913394928)
[78/387] taukdial-040-3.wav -> en (0.999355137348175)
[79/387] taukdial-041-1.wav -> en (0.9989860653877258)
[80/387] taukdial-041-2.wav -> en (0.9994907379150391)
[81/387] taukdial-041-3.wav -> en (0.999771773815155)
[82/387] taukdial-044-1.wav -> zh (0.991600751876831)
[83/387] taukdial-044-2.wav -> zh (0.9880870580673218)
[84/387] taukdial-044-3.wav -> zh (0.9909732937812805)
[85/387] taukdial-045-1.wav -> zh (0.9883692264556885)
[86/387] taukdial-045-2.wav -> zh (0.9868248105049133)
[87/387] taukdial-045-3.wav -> zh (0.9746413826942444)
[88/387] taukdial-046-1.wav -> en (0.9960176348686218)
[89/387] taukdial-046-2.wav -> en (0.9987388253211975)
[90/387] taukdial-046-3.wav -> en (0.996121346950531)
[91/387] taukdial-047-1.wav -> zh (0.99146568775177)
[92/387] taukdial-047-2.wav -> zh (0.9931522607803345)
[93/387] taukdial-047-3.wav -> zh (0.9897712469100952)
[94/387] taukdial-048-1.wav -> zh (0.9961007833480835)
[95/387] taukdial-048-2.wav -> zh (0.995173990726471)
[96/387] taukdial-048-3.wav -> zh (0.9847007989883423)
[97/387] taukdial-050-1.wav -> en (0.9988052845001221)
[98/387] taukdial-050-2.wav -> en (0.9985467791557312)
[99/387] taukdial-050-3.wav -> en (0.9992170333862305)
[100/387] taukdial-051-1.wav -> zh (0.9968186616897583)
[101/387] taukdial-051-2.wav -> zh (0.9979277849197388)
[102/387] taukdial-051-3.wav -> zh (0.9971713423728943)
[103/387] taukdial-052-1.wav -> en (0.9997482895851135)
[104/387] taukdial-052-2.wav -> en (0.9995342493057251)
[105/387] taukdial-052-3.wav -> en (0.9972911477088928)
[106/387] taukdial-053-1.wav -> zh (0.9971451163291931)
[107/387] taukdial-053-2.wav -> zh (0.996554970741272)
[108/387] taukdial-053-3.wav -> zh (0.9910248517990112)
[109/387] taukdial-054-1.wav -> zh (0.996206521987915)
[110/387] taukdial-054-2.wav -> zh (0.9941012263298035)
[111/387] taukdial-054-3.wav -> zh (0.9962628483772278)
[112/387] taukdial-056-1.wav -> zh (0.9902465343475342)
[113/387] taukdial-056-2.wav -> zh (0.9695232510566711)
[114/387] taukdial-056-3.wav -> zh (0.9813488125801086)
[115/387] taukdial-057-1.wav -> en (0.9984003901481628)
[116/387] taukdial-057-2.wav -> en (0.9997509121894836)
[117/387] taukdial-057-3.wav -> en (0.9982075691223145)
[118/387] taukdial-063-1.wav -> zh (0.9852684140205383)
[119/387] taukdial-063-2.wav -> zh (0.9983166456222534)
[120/387] taukdial-063-3.wav -> zh (0.9930458664894104)
[121/387] taukdial-064-1.wav -> zh (0.9880045056343079)
[122/387] taukdial-064-2.wav -> zh (0.989727795124054)
[123/387] taukdial-064-3.wav -> zh (0.9698368906974792)
[124/387] taukdial-065-1.wav -> zh (0.9931756854057312)
[125/387] taukdial-065-2.wav -> zh (0.9924627542495728)
[126/387] taukdial-065-3.wav -> zh (0.9886462688446045)
[127/387] taukdial-066-1.wav -> zh (0.9884682297706604)
[128/387] taukdial-066-2.wav -> zh (0.960418164730072)
[129/387] taukdial-066-3.wav -> zh (0.9171565175056458)
[130/387] taukdial-067-1.wav -> zh (0.9490980505943298)
[131/387] taukdial-067-2.wav -> zh (0.9923810362815857)
[132/387] taukdial-067-3.wav -> zh (0.9776109457015991)
[133/387] taukdial-068-1.wav -> en (0.9988866448402405)
[134/387] taukdial-068-2.wav -> en (0.9996582269668579)
[135/387] taukdial-068-3.wav -> en (0.9994146823883057)
[136/387] taukdial-069-1.wav -> en (0.9962570667266846)
[137/387] taukdial-069-2.wav -> en (0.9977395534515381)
[138/387] taukdial-069-3.wav -> en (0.9970393180847168)
[139/387] taukdial-070-1.wav -> en (0.9985935091972351)
[140/387] taukdial-070-2.wav -> en (0.9993767142295837)
[141/387] taukdial-070-3.wav -> en (0.9937680959701538)
[142/387] taukdial-071-1.wav -> en (0.9986844658851624)
[143/387] taukdial-071-2.wav -> en (0.9994914531707764)
[144/387] taukdial-071-3.wav -> en (0.9982262253761292)
[145/387] taukdial-072-1.wav -> zh (0.9868354797363281)
[146/387] taukdial-072-2.wav -> zh (0.9962241649627686)
[147/387] taukdial-072-3.wav -> zh (0.9920769929885864)
[148/387] taukdial-073-1.wav -> zh (0.9904012084007263)
[149/387] taukdial-073-2.wav -> zh (0.9894834160804749)
[150/387] taukdial-073-3.wav -> zh (0.9631434679031372)
[151/387] taukdial-074-1.wav -> en (0.9989745616912842)
[152/387] taukdial-074-2.wav -> en (0.999782383441925)
[153/387] taukdial-074-3.wav -> en (0.9991877675056458)
[154/387] taukdial-076-1.wav -> en (0.9981763362884521)
[155/387] taukdial-076-2.wav -> en (0.9988806843757629)
[156/387] taukdial-076-3.wav -> en (0.9982349872589111)
[157/387] taukdial-077-1.wav -> en (0.9983397722244263)
[158/387] taukdial-077-2.wav -> en (0.999377429485321)
[159/387] taukdial-077-3.wav -> en (0.9983783960342407)
[160/387] taukdial-078-1.wav -> en (0.9976133108139038)
[161/387] taukdial-078-2.wav -> en (0.9979212880134583)
[162/387] taukdial-078-3.wav -> en (0.9981391429901123)
[163/387] taukdial-079-1.wav -> en (0.9985311031341553)
[164/387] taukdial-079-2.wav -> en (0.9981560111045837)
[165/387] taukdial-079-3.wav -> en (0.9976741671562195)
[166/387] taukdial-080-1.wav -> zh (0.9975253939628601)
[167/387] taukdial-080-2.wav -> zh (0.9885777235031128)
[168/387] taukdial-080-3.wav -> zh (0.795222818851471)
[169/387] taukdial-082-1.wav -> zh (0.9942843317985535)
[170/387] taukdial-082-2.wav -> zh (0.9903954863548279)
[171/387] taukdial-082-3.wav -> zh (0.995526134967804)
[172/387] taukdial-083-1.wav -> en (0.99880051612854)
[173/387] taukdial-083-2.wav -> en (0.9986435770988464)
[174/387] taukdial-083-3.wav -> en (0.9982696771621704)
[175/387] taukdial-085-1.wav -> en (0.9995083808898926)
[176/387] taukdial-085-2.wav -> en (0.999270498752594)
[177/387] taukdial-085-3.wav -> en (0.9992853999137878)
[178/387] taukdial-086-1.wav -> zh (0.982593834400177)
[179/387] taukdial-086-2.wav -> zh (0.9948093891143799)
[180/387] taukdial-086-3.wav -> zh (0.986825168132782)
[181/387] taukdial-088-1.wav -> en (0.9996516704559326)
[182/387] taukdial-088-2.wav -> en (0.9994231462478638)
[183/387] taukdial-088-3.wav -> en (0.9997729659080505)
[184/387] taukdial-089-1.wav -> en (0.9990749359130859)
[185/387] taukdial-089-2.wav -> en (0.9994482398033142)
[186/387] taukdial-089-3.wav -> en (0.9986315369606018)
[187/387] taukdial-090-1.wav -> zh (0.9897418022155762)
[188/387] taukdial-090-2.wav -> zh (0.9982536435127258)
[189/387] taukdial-090-3.wav -> zh (0.9947810769081116)
[190/387] taukdial-091-1.wav -> en (0.9980564117431641)
[191/387] taukdial-091-2.wav -> en (0.9987744688987732)
[192/387] taukdial-091-3.wav -> en (0.9985103011131287)
[193/387] taukdial-092-1.wav -> zh (0.9967232346534729)
[194/387] taukdial-092-2.wav -> zh (0.9924172163009644)
[195/387] taukdial-092-3.wav -> zh (0.9954303503036499)
[196/387] taukdial-093-1.wav -> zh (0.9893409609794617)
[197/387] taukdial-093-2.wav -> zh (0.99664306640625)
[198/387] taukdial-093-3.wav -> zh (0.988129198551178)
[199/387] taukdial-094-1.wav -> zh (0.9937071204185486)
[200/387] taukdial-094-2.wav -> zh (0.9892134070396423)
[201/387] taukdial-094-3.wav -> zh (0.9937456846237183)
[202/387] taukdial-095-1.wav -> en (0.9983933568000793)
[203/387] taukdial-095-2.wav -> en (0.9965852499008179)
[204/387] taukdial-095-3.wav -> en (0.9967808723449707)
[205/387] taukdial-096-1.wav -> zh (0.9628039002418518)
[206/387] taukdial-096-2.wav -> zh (0.9941428303718567)
[207/387] taukdial-096-3.wav -> zh (0.9921910166740417)
[208/387] taukdial-097-1.wav -> zh (0.9886773824691772)
[209/387] taukdial-097-2.wav -> zh (0.9844501614570618)
[210/387] taukdial-097-3.wav -> zh (0.9779112935066223)
[211/387] taukdial-098-1.wav -> zh (0.9953688979148865)
[212/387] taukdial-098-2.wav -> zh (0.9987269043922424)
[213/387] taukdial-098-3.wav -> zh (0.9925590753555298)
[214/387] taukdial-099-1.wav -> en (0.9980499744415283)
[215/387] taukdial-099-2.wav -> en (0.9974924325942993)
[216/387] taukdial-099-3.wav -> en (0.9976227879524231)
[217/387] taukdial-100-1.wav -> bo (0.6642001867294312)
[218/387] taukdial-100-2.wav -> zh (0.9859974384307861)
[219/387] taukdial-100-3.wav -> zh (0.9702966213226318)
[220/387] taukdial-101-1.wav -> en (0.997836172580719)
[221/387] taukdial-101-2.wav -> en (0.9995906949043274)
[222/387] taukdial-101-3.wav -> en (0.9981446266174316)
[223/387] taukdial-102-1.wav -> en (0.9993071556091309)
[224/387] taukdial-102-2.wav -> en (0.9993964433670044)
[225/387] taukdial-102-3.wav -> en (0.9991081357002258)
[226/387] taukdial-104-1.wav -> en (0.999011754989624)
[227/387] taukdial-104-2.wav -> en (0.9980365633964539)
[228/387] taukdial-104-3.wav -> en (0.9994575381278992)
[229/387] taukdial-105-1.wav -> zh (0.9959548711776733)
[230/387] taukdial-105-2.wav -> zh (0.9945032596588135)
[231/387] taukdial-105-3.wav -> zh (0.9890016317367554)
[232/387] taukdial-106-1.wav -> zh (0.9806862473487854)
[233/387] taukdial-106-2.wav -> zh (0.988179087638855)
[234/387] taukdial-106-3.wav -> zh (0.9816967844963074)
[235/387] taukdial-107-1.wav -> zh (0.9928064346313477)
[236/387] taukdial-107-2.wav -> zh (0.9960229396820068)
[237/387] taukdial-107-3.wav -> zh (0.9787753820419312)
[238/387] taukdial-108-1.wav -> zh (0.9642221331596375)
[239/387] taukdial-108-2.wav -> zh (0.978683352470398)
[240/387] taukdial-108-3.wav -> zh (0.9496456980705261)
[241/387] taukdial-109-1.wav -> zh (0.988811731338501)
[242/387] taukdial-109-2.wav -> zh (0.995344340801239)
[243/387] taukdial-109-3.wav -> zh (0.9971644282341003)
[244/387] taukdial-110-1.wav -> zh (0.9759954810142517)
[245/387] taukdial-110-2.wav -> zh (0.9556285738945007)
[246/387] taukdial-110-3.wav -> zh (0.9548516869544983)
[247/387] taukdial-111-1.wav -> zh (0.9920712113380432)
[248/387] taukdial-111-2.wav -> zh (0.9901890158653259)
[249/387] taukdial-111-3.wav -> zh (0.9909712076187134)
[250/387] taukdial-112-1.wav -> en (0.9969419836997986)
[251/387] taukdial-112-2.wav -> en (0.9990859031677246)
[252/387] taukdial-112-3.wav -> en (0.9958498477935791)
[253/387] taukdial-113-1.wav -> en (0.9986950755119324)
[254/387] taukdial-113-2.wav -> en (0.9994480013847351)
[255/387] taukdial-113-3.wav -> en (0.9993597865104675)
[256/387] taukdial-115-1.wav -> en (0.9994348883628845)
[257/387] taukdial-115-2.wav -> en (0.9994682669639587)
[258/387] taukdial-115-3.wav -> en (0.9995076656341553)
[259/387] taukdial-116-1.wav -> en (0.9987934827804565)
[260/387] taukdial-116-2.wav -> en (0.9996154308319092)
[261/387] taukdial-116-3.wav -> en (0.9982553124427795)
[262/387] taukdial-117-1.wav -> en (0.9996324777603149)
[263/387] taukdial-117-2.wav -> en (0.9993107318878174)
[264/387] taukdial-117-3.wav -> en (0.9996272325515747)
[265/387] taukdial-118-1.wav -> en (0.9975850582122803)
[266/387] taukdial-118-2.wav -> en (0.998794436454773)
[267/387] taukdial-118-3.wav -> en (0.9981447458267212)
[268/387] taukdial-120-1.wav -> en (0.9988871216773987)
[269/387] taukdial-120-2.wav -> en (0.9992700219154358)
[270/387] taukdial-120-3.wav -> en (0.9985601305961609)
[271/387] taukdial-121-1.wav -> zh (0.98052978515625)
[272/387] taukdial-121-2.wav -> zh (0.9882633686065674)
[273/387] taukdial-121-3.wav -> zh (0.9930818676948547)
[274/387] taukdial-122-1.wav -> my (0.5936365723609924)
[275/387] taukdial-122-2.wav -> zh (0.5191174745559692)
[276/387] taukdial-122-3.wav -> zh (0.6921693086624146)
[277/387] taukdial-124-1.wav -> en (0.9957824945449829)
[278/387] taukdial-124-2.wav -> en (0.9995286464691162)
[279/387] taukdial-124-3.wav -> en (0.9991625547409058)
[280/387] taukdial-125-1.wav -> en (0.9977444410324097)
[281/387] taukdial-125-2.wav -> en (0.9965221881866455)
[282/387] taukdial-125-3.wav -> en (0.9997305274009705)
[283/387] taukdial-126-1.wav -> en (0.9965768456459045)
[284/387] taukdial-126-2.wav -> en (0.9982414245605469)
[285/387] taukdial-126-3.wav -> en (0.9937704205513)
[286/387] taukdial-127-1.wav -> zh (0.9961736798286438)
[287/387] taukdial-127-2.wav -> zh (0.9982288479804993)
[288/387] taukdial-127-3.wav -> zh (0.9902064204216003)
[289/387] taukdial-128-1.wav -> zh (0.9888961315155029)
[290/387] taukdial-128-2.wav -> zh (0.9933131337165833)
[291/387] taukdial-128-3.wav -> zh (0.9595789909362793)
[292/387] taukdial-129-1.wav -> zh (0.9880350232124329)
[293/387] taukdial-129-2.wav -> zh (0.9676730632781982)
[294/387] taukdial-129-3.wav -> zh (0.9790431261062622)
[295/387] taukdial-130-1.wav -> zh (0.9866395592689514)
[296/387] taukdial-130-2.wav -> zh (0.9804685115814209)
[297/387] taukdial-130-3.wav -> zh (0.9843472242355347)
[298/387] taukdial-131-1.wav -> zh (0.972647488117218)
[299/387] taukdial-131-2.wav -> zh (0.9919954538345337)
[300/387] taukdial-131-3.wav -> zh (0.9845753908157349)
[301/387] taukdial-132-1.wav -> zh (0.9843761920928955)
[302/387] taukdial-132-2.wav -> zh (0.9982865452766418)
[303/387] taukdial-132-3.wav -> zh (0.9600148797035217)
[304/387] taukdial-134-1.wav -> zh (0.9905101656913757)
[305/387] taukdial-134-2.wav -> zh (0.9923090934753418)
[306/387] taukdial-134-3.wav -> zh (0.9931650757789612)
[307/387] taukdial-136-1.wav -> zh (0.9530856609344482)
[308/387] taukdial-136-2.wav -> zh (0.9354619383811951)
[309/387] taukdial-136-3.wav -> zh (0.9589183330535889)
[310/387] taukdial-137-1.wav -> en (0.998158872127533)
[311/387] taukdial-137-2.wav -> en (0.9977555871009827)
[312/387] taukdial-137-3.wav -> en (0.9992233514785767)
[313/387] taukdial-138-1.wav -> en (0.9990313053131104)
[314/387] taukdial-138-2.wav -> en (0.9996680021286011)
[315/387] taukdial-138-3.wav -> en (0.9991645812988281)
[316/387] taukdial-139-1.wav -> en (0.999729335308075)
[317/387] taukdial-139-2.wav -> en (0.9996511936187744)
[318/387] taukdial-139-3.wav -> en (0.9993002414703369)
[319/387] taukdial-140-1.wav -> en (0.9980947375297546)
[320/387] taukdial-140-2.wav -> en (0.9993118047714233)
[321/387] taukdial-140-3.wav -> en (0.9984415173530579)
[322/387] taukdial-141-1.wav -> zh (0.9689812064170837)
[323/387] taukdial-141-2.wav -> zh (0.9801827669143677)
[324/387] taukdial-141-3.wav -> zh (0.9756284952163696)
[325/387] taukdial-142-1.wav -> zh (0.9948430061340332)
[326/387] taukdial-142-2.wav -> zh (0.9965764880180359)
[327/387] taukdial-142-3.wav -> zh (0.9960630536079407)
[328/387] taukdial-143-1.wav -> zh (0.9807890057563782)
[329/387] taukdial-143-2.wav -> zh (0.9740831255912781)
[330/387] taukdial-143-3.wav -> zh (0.9872493147850037)
[331/387] taukdial-144-1.wav -> zh (0.9907382130622864)
[332/387] taukdial-144-2.wav -> zh (0.9954473376274109)
[333/387] taukdial-144-3.wav -> zh (0.9846413731575012)
[334/387] taukdial-145-1.wav -> en (0.9968850016593933)
[335/387] taukdial-145-2.wav -> en (0.996856689453125)
[336/387] taukdial-145-3.wav -> en (0.9970855116844177)
[337/387] taukdial-148-1.wav -> en (0.9972802400588989)
[338/387] taukdial-148-2.wav -> en (0.9991573095321655)
[339/387] taukdial-148-3.wav -> en (0.9980227947235107)
[340/387] taukdial-149-1.wav -> en (0.9992840886116028)
[341/387] taukdial-149-2.wav -> en (0.9994266033172607)
[342/387] taukdial-149-3.wav -> en (0.999854564666748)
[343/387] taukdial-151-1.wav -> en (0.9981108903884888)
[344/387] taukdial-151-2.wav -> en (0.9980238676071167)
[345/387] taukdial-151-3.wav -> en (0.9992706179618835)
[346/387] taukdial-153-1.wav -> zh (0.9884703159332275)
[347/387] taukdial-153-2.wav -> zh (0.9982831478118896)
[348/387] taukdial-153-3.wav -> zh (0.9901052117347717)
[349/387] taukdial-154-1.wav -> en (0.999562680721283)
[350/387] taukdial-154-2.wav -> en (0.9993889331817627)
[351/387] taukdial-154-3.wav -> en (0.998664379119873)
[352/387] taukdial-156-1.wav -> zh (0.9934478402137756)
[353/387] taukdial-156-2.wav -> zh (0.9970889687538147)
[354/387] taukdial-156-3.wav -> zh (0.9961879849433899)
[355/387] taukdial-157-1.wav -> zh (0.9670194983482361)
[356/387] taukdial-157-2.wav -> zh (0.9634929299354553)
[357/387] taukdial-157-3.wav -> zh (0.9074348211288452)
[358/387] taukdial-158-1.wav -> en (0.9992759823799133)
[359/387] taukdial-158-2.wav -> en (0.9993374943733215)